LoadLeveler plug-in: stop the script if llsubmit is missing

diff --git a/plugins/cli/pod-loadleveler-submit b/plugins/cli/pod-loadleveler-submit
--- a/plugins/cli/pod-loadleveler-submit
+++ b/plugins/cli/pod-loadleveler-submit
@@ -20,6 +20,13 @@
 #
 LL_SUBMIT=llsubmit
 eval LL_JOBFILE=$POD_LOCATION/etc/Job.loadleveler
+
+t=$($LL_SUBMIT -? &>/dev/null)
+if (( $? != 0 )); then
+   echo "Error: Can't execute \"$LL_SUBMIT\""
+   exit 1
+fi
+
 #=============================================================================
 # ***** MAIN  *****
 #=============================================================================
