implemented a log engine, which works via a named pipe

diff --git a/bin/pod-ssh-clean-worker b/bin/pod-ssh-clean-worker
--- a/bin/pod-ssh-clean-worker
+++ b/bin/pod-ssh-clean-worker
@@ -24,6 +24,22 @@ TIMEOUT=30
 SSH_CMD="ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=$TIMEOUT -o PasswordAuthentication=no -q $1 $3"
 SCP_CMD="scp -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=$TIMEOUT -o PasswordAuthentication=no $3"
 WAITTIMEOUT=10
+# a pod-ssh communication pipe (log engine)
+pipe="$POD_LOCATION/.ssh_plugin_pipe"
+if [[ ! -p $pipe ]]; then
+    echo "$TOOL_NAME error: pod-ssh log engine is not running"
+    exit 1
+fi
+logMsg()
+{
+# date format
+#RFC-2822:
+# *    www, dd mmm yyyy hh:mm:ss +zzzz
+#
+# Don't use date -R since it's a GNU specific implementation (doesn't work on Mac, for example)
+    echo "*** [$(date '+%a, %d %b %Y %T %z')]   $1" > $pipe
+}
+
 
 # a special case, executed on the remote host
 # check for pid file of worker's script.
@@ -52,28 +68,28 @@ fi
 # this part is executed locally
 SELF_PATH=$(readlink -f $0)
 
-$SSH_CMD "test -d $2"
+$SSH_CMD "test -d $2" &> $pipe
 if [ $? -ne 0 ]; then
    exit 0
 fi
 
-$SCP_CMD $SELF_PATH $1:$2/
+$SCP_CMD $SELF_PATH $1:$2/  &> $pipe
 if [ $? -ne 0 ]; then
-    echo "$TOOL_NAME error: failed to send worker's cleaning script $SELF_PATH"
+    logMsg "$TOOL_NAME error: failed to send worker's cleaning script $SELF_PATH"
     exit 1
 fi
 
 # Submit a cleaning script
-$SSH_CMD "$2/$TOOL_NAME clean $2"
+$SSH_CMD "$2/$TOOL_NAME clean $2"  &> $pipe
 if [ $? -ne 0 ]; then
-    echo "$TOOL_NAME error: failed to stop PoD worker."
+    logMsg "$TOOL_NAME error: failed to stop PoD worker."
     exit 1
 fi
 
 # remove the working directory
-$SSH_CMD "rm -rf $2"
+$SSH_CMD "rm -rf $2"  &> $pipe
 if [ $? -ne 0 ]; then
-    echo "$TOOL_NAME error: failed to remove the remote working dir: $2"
+    logMsg "$TOOL_NAME error: failed to remove the remote working dir: $2"
     exit 1
 fi
 
diff --git a/bin/pod-ssh-submit-worker b/bin/pod-ssh-submit-worker
--- a/bin/pod-ssh-submit-worker
+++ b/bin/pod-ssh-submit-worker
@@ -27,24 +27,42 @@ TIMEOUT=30
 
 SSH_CMD="ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=$TIMEOUT -o PasswordAuthentication=no -n -f -q $1 $4"
 
+# a pod-ssh communication pipe (log engine)
+pipe="$POD_LOCATION/.ssh_plugin_pipe"
+if [[ ! -p $pipe ]]; then
+    echo "$TOOL_NAME error: pod-ssh log engine is not running"
+    exit 1
+fi
+logMsg()
+{
+# date format
+#RFC-2822:
+# *    www, dd mmm yyyy hh:mm:ss +zzzz
+#
+# Don't use date -R since it's a GNU specific implementation (doesn't work on Mac, for example)
+    echo "*** [$(date '+%a, %d %b %Y %T %z')]   $1" > $pipe
+}
+
+logMsg "$TOOL_NAME is started for $1"
+
 # check that the worker package is ready
 if [ ! -r $WRK_P ]; then
-echo "$TOOL_NAME error: can't read a PoD worker package \"$WRK_P\""
-exit 1
+   logMsg "$TOOL_NAME error: can't read a PoD worker package \"$WRK_P\""
+   exit 1
 fi
 
 # send a worker package and worker's script
 # use rsync since it can automatically create a remote working dir
-rsync -aq -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=no $4" $WRK_P $WRK_S_L $1:$2/
+rsync -aq -e "ssh -o BatchMode=yes -o StrictHostKeyChecking=no $4" $WRK_P $WRK_S_L $1:$2/ &> $pipe
 if [ $? -ne 0 ]; then
-    echo "$TOOL_NAME error: failed to send worker's package"
+    logMsg "$TOOL_NAME error: failed to send worker's package"
     exit 1
 fi
 
 # execute the worker script
-$SSH_CMD "nohup bash -c \"cd $2 && ./$WRK_S_R &> ssh_worker.log \" &> ssh_worker.log  < /dev/null &"
+$SSH_CMD "nohup bash -c \"cd $2 && ./$WRK_S_R &> ssh_worker.log \" &> ssh_worker.log  < /dev/null &" &> $pipe
 if [ $? -ne 0 ]; then
-    echo "$TOOL_NAME error: faild to start PoD worker"
+    logMsg "$TOOL_NAME error: faild to start PoD worker"
     exit 1
 fi
 
