a prototype implementation of the OGE/SGE plug-in (CLI only)

diff --git a/bin/pod-submit b/bin/pod-submit
--- a/bin/pod-submit
+++ b/bin/pod-submit
@@ -13,7 +13,7 @@
 #*************************************************************************/
 #
 # Usage: pod-submit [-r [lsf:pbs]] [-q] [-n X] [-h]
-# -r rms : Name of the resource management system (supported: lsf, pbs).
+# -r rms : Name of the resource management system (supported: lsf, pbs, oge).
 # -q     : Submit the jobs to specified queue.
 # -n X   : Desired number or PROOF workers.
 # -h     : Show summary of options.
@@ -57,8 +57,8 @@ NUM_WRK=10
 while getopts ":q:n:hr:" opt; do
   case $opt in
   q)
-     QUEUE="$OPTARG"
-     ;;
+    QUEUE="$OPTARG"
+    ;;
   n)
     NUM_WRK=$OPTARG
     ;;
@@ -127,7 +127,26 @@ elif  [ "$RMS" = "pbs" ]; then
   else
     echo "Error submitting job. $jobid"
   fi
-  
+ 
+elif [ "$RMS" = "oge" ]; then
+  # SGE/OGE
+  #
+  # We assume, that shared home file system is used.
+  # qsub with parameters:
+  # -V          export all environment variables
+  # -terse      tersed output, print only the job-id
+  oge_job_array_param="-t 1-$NUM_WRK"
+  job_name="PoD_OGE_Job"
+  jobid=$(qsub -V -N $job_name -terse $oge_job_array_param -q $QUEUE -o $LOG_DIR -e $LOG_DIR $POD_LOCATION/etc/Job.oge | cut -f3 -d" "|cut -f1 -d.)
+  # we need to create a logs output dir
+  stat=$?
+  if test $stat -eq 0; then
+    echo "Job ID: $jobid"
+    mkdir -p  $LOG_DIR/$jobid
+  else
+    echo "Error submitting job. $jobid"
+  fi
+
 fi
 
 exit 0
