ssh plug-in: get exit status properly when commands are piped, use bash's PIPESTATUS

diff --git a/bin/pod-ssh-status-worker b/bin/pod-ssh-status-worker
--- a/bin/pod-ssh-status-worker
+++ b/bin/pod-ssh-status-worker
@@ -71,7 +71,7 @@ fi
 #=============================================================================
 TOOL_NAME="pod-ssh-status-worker"
 WRK_PID=PoDWorker.pid
-TIMEOUT=30
+TIMEOUT=10
 
 SSH_CMD="ssh -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=$TIMEOUT -o PasswordAuthentication=no -q $SSH_CON_STR $SSHOPT"
 #=============================================================================
@@ -107,31 +107,6 @@ logMsg()
     echo -e "$WORKER_ID\t[$(date '+%a, %d %b %Y %T %z')]\t$1" > $pipe
 }
 #=============================================================================
-# ***** remote part *****
-#=============================================================================
-# a special case, executed on the remote host
-# check for pid file of worker's script.
-# If the file is available, read pid from it and send a TERM signal using that pid.
-# If the file is unavailable, exit with 0 - it is not an error for us.
-if [ "$CLEAN" = "clean" ]; then
-    pid_file="$RDIR/$WRK_PID"
-    if [  -e $pid_file ]; then
-	pid=$(cat $pid_file)
-	kill -15 $pid
-	cnt=0
-	while $(kill -0 $pid &>/dev/null); do
-	   cnt=$(expr $cnt + 1)
-	   if [ $cnt -gt $WAITTIMEOUT ]; then
-	      echo "$TOOL_NAME error: failed to wait for pid $pid"
-	      exit 1
-	   fi
-	   sleep 1
-	done
-    fi
-
-    exit 0
-fi
-#=============================================================================
 # ***** local part *****
 #=============================================================================
 # this part is executed locally
@@ -139,17 +114,30 @@ logMsg "$TOOL_NAME is started for $SSH_CON_STR (dir: $RDIR, sshopt: $SSHOPT)"
 SELF_PATH=$(readlink -f $0)
 
 $SSH_CMD "test -d $RDIR" 2>&1 | logMsgPipe
-if [ $? -ne 0 ]; then
-   logMsg "CLEAN"
+if [ ${PIPESTATUS[0]} -ne 0 ]; then
+   logMsg "Worker status: CLEAN"
    exit 0
 fi
 
-$SSH_CMD "pid_file=\"$RDIR/$WRK_PID\";if [  -e $pid_file ]; then; exit 0; fi; exit 1;" 2>&1 | logMsgPipe
-if [ $? -ne 0 ]; then
-   logMsg "DONE"
-else
-   logMsg "RUN"
+
+pid_file="$RDIR/$WRK_PID"
+
+$SSH_CMD "test -r $pid_file && exit 4 || exit 5" 2>&1 | logMsgPipe
+
+ret=${PIPESTATUS[0]}
+if (( $ret == 1 )); then
+   logMsg "Failed to check."
+   exit 0
 fi
 
+if (( $ret == 5 )); then
+   logMsg "Worker status: DONE"
+   exit 0
+elif (( $ret == 4 )); then
+   logMsg "Worker status: RUN"
+   exit 0
+fi
+
+logMsg "Worker status: UNKNOWN"
 exit 0
 
