more fixes for an install-for-all-users feature + PoD UD: removed server/worker.proof_cfg_path

diff --git a/bin/pod-server b/bin/pod-server
--- a/bin/pod-server
+++ b/bin/pod-server
@@ -37,10 +37,19 @@ XPROOF_PORTS_RANGE_MIN=$(pod-user-defaults --key server.xproof_ports_range_min)
 XPROOF_PORTS_RANGE_MAX=$(pod-user-defaults --key server.xproof_ports_range_max)
 PROOFAGENT_PORTS_RANGE_MIN=$(pod-user-defaults --key server.agent_ports_range_min)
 PROOFAGENT_PORTS_RANGE_MAX=$(pod-user-defaults --key server.agent_ports_range_max)
-eval WORK_DIR=$(pod-user-defaults --key server.work_dir)
-XPD_CFG="$WORK_DIR/etc/xpd.cf"
+WORK_DIR=$(pod-user-defaults -V --key server.work_dir)
+if (( $? != 0 )) ; then
+   echo "ERROR: Your PoD user defaults can't be used with this version of PoD."
+   echo "If you want to continue to use this version of PoD, you have the following options:"
+   echo "1. Fix your configuration file."
+   echo "2. Recreate the file using: pod-user-defaults -f -d -c \"$(pod-user-defaults -p)\""
+   exit 1
+fi
+eval WORK_DIR="$WORK_DIR"
+eval XPD_CFG="$WORK_DIR/etc/xpd.cf"
 eval POD_SRV_LOGDIR=$(pod-user-defaults --key server.logfile_dir)
-SERVERINFO_FILE="$WORK_DIR/etc/server_info.cfg"
+eval SERVERINFO_FILE="$WORK_DIR/etc/server_info.cfg"
+eval POD_PROOFCFG_FILE="$WORK_DIR/proof.conf"
 #######
 # a number of seconds we wait until xpd is started 
 XPD_START_TIMEOUT=3
@@ -202,6 +211,24 @@ get_bins()
    done
    popd &> /dev/null
 }
+#=============================================================================
+# ***** create_dir  *****
+#=============================================================================
+create_dir()
+{
+   if [ ! -d "$1" ]; then
+      mkdir -p "$1"
+   fi
+}
+# ************************************************************************
+# ***** create_dir_hierarchy *****
+# ************************************************************************
+create_dir_hierarchy()
+{
+   create_dir "$WORK_DIR/etc"
+   create_dir "$WORK_DIR/wrk"
+   create_dir "$POD_SRV_LOGDIR"
+}
 # ************************************************************************
 # ***** START  *****
 # ************************************************************************
@@ -222,6 +249,7 @@ start()
 
     # updating XPD configuration file
     echo "updating xproofd configuration file..."
+    update_xpd_cfg
     regexp_xpd_port="s/\(xpd.port[[:space:]]*\)[0-9]*/\1$NEW_XPROOF_PORT/g"
     regexp_server_host="s/\(if[[:space:]]\).*\([[:space:]]#SERVERHOST DONT EDIT THIS LINE\)/\1$SERVER_HOST_NAME\2/g"
     sed -e "$regexp_xpd_port" -e "$regexp_xproof_port" -e "$regexp_server_host" $XPD_CFG > "$XPD_CFG.temp"
@@ -307,13 +335,24 @@ status()
     fi
 }
 # ************************************************************************
-# ***** MAIN  *****
-# checking the number of parameters
+# ***** update_xpd_cfg  *****
 # ************************************************************************
-if [ $# -ne 1 ]; then
-    echo "Usage: pod-server start|stop|status|getbins"
-    exit 1
-fi
+update_xpd_cfg()
+{
+   # make a local version of xpd config file for the first time
+   if [ ! -r "$XPD_CFG" ]; then
+      cp $POD_LOCATION/etc/xpd.cf.in $XPD_CFG
+      _TMP_DIR=$(mktemp -d /tmp/PoD_XXXXXXXXXX)
+      chmod 777 $_TMP_DIR
+      eval sed -i.bup 's%_POD_TMP_DIR%$_TMP_DIR%g' $XPD_CFG 
+   fi
+}
+# ************************************************************************
+# ***** MAIN  *****
+# ************************************************************************
+
+# create work dir hierarchy
+create_dir_hierarchy
 
 # work_dir must be a valid dir
 if [ ! -e "$WORK_DIR" ]; then
@@ -339,6 +378,9 @@ case "$1" in
         get_bins
         RETVAL=$?
         ;;
+    *)
+        echo $"Usage: $0 {start|stop|status|getbins}"
+        exit 1
 esac
 
 exit $RETVAL
