pod: PoD tries to automatically detect whether PoD's server is installed on a shared home file system, which is also      mounted on WNs. pod: PoD WNs now try to use first binaries from PoD UI, if OS, ARCH of Server and UI are the same      and a shared home file system is detected. It speeds up the start up time of PoD jobs. If this try fails, PoD WN will use      pre-compiled bins, which come with PoD' worker package. pod-user-defaults: updated user defaults configuration file - v0.6. pod-user-defaults: removed the pbs_plugin.shared_home option. pod-user-defaults: added the oge_plugin.upload_job_log option.

diff --git a/bin/pod-submit b/bin/pod-submit
--- a/bin/pod-submit
+++ b/bin/pod-submit
@@ -22,7 +22,6 @@
 # PoD environment variables exported to the workers:
 #  POD_UI_LOG_LOCATION : log dir on the PoD UI
 #  POD_UI_LOCATION     : $POD_LOCATION of the PoD UI
-#  POD_PBS_SHARED_HOME : (yes/no) whether shared home file system is used on PBS
 
 #=============================================================================
 # ***** USAGE *****
@@ -47,41 +46,41 @@ EOF
 #=============================================================================
 # checking the number of parameters
 if [ $# -ne 6 ]; then
-    usage
-    exit 1
+   usage
+   exit 1
 fi
 
 RMS="lsf"
 QUEUE="proof"
 NUM_WRK=10
 while getopts ":q:n:hr:" opt; do
-  case $opt in
-  q)
-    QUEUE="$OPTARG"
-    ;;
-  n)
-    NUM_WRK=$OPTARG
-    ;;
-  r) 
-    RMS=$OPTARG
-    ;;
-  h) 
-    usage
-    exit 0
-    ;;
-  \?)
-    echo "Invalid option: -$OPTARG" >&2
-    exit 1
-    ;;
-  esac
+   case $opt in
+      q)
+       QUEUE="$OPTARG"
+       ;;
+      n)
+       NUM_WRK=$OPTARG
+       ;;
+      r) 
+       RMS=$OPTARG
+       ;;
+      h) 
+       usage
+       exit 0
+       ;;
+     \?)
+       echo "Invalid option: -$OPTARG" >&2
+       exit 1
+       ;;
+   esac
 done
 
 # check supported RMS
 if [ "$RMS" != "lsf" ] && [ "$RMS" != "pbs" ] && [ "$RMS" != "oge" ]; then
-  echo "Error: \"$RMS\" is not supported by this command."
-  echo ""
-  usage
-  exit 1
+   echo "Error: \"$RMS\" is not supported by this command."
+   echo ""
+   usage
+   exit 1
 fi
 
 
@@ -92,69 +91,66 @@ export POD_UI_LOG_LOCATION=$LOG_DIR
 export POD_UI_LOCATION=$POD_LOCATION
 
 if [ "$RMS" = "lsf" ]; then
-  # LSF 
-  JOB_NAME="$BASHPID[1-$NUM_WRK]"
-  OUTPUT=""
-  if [ $EMAIL_JOB_OUTPUT -eq 0 ]; then
+   #
+   # LSF 
+   #
+   JOB_NAME="$BASHPID[1-$NUM_WRK]"
+   OUTPUT=""
+   if [ $EMAIL_JOB_OUTPUT -eq 0 ]; then
       OUTPUT=" -o $LOG_DIR/%J/std_%I.out -e $LOG_DIR/%J/std_%I.err"
-  fi
-  bsub -q $QUEUE -J $JOB_NAME $OUTPUT $POD_LOCATION/etc/Job.lsf
+   fi
+   bsub -q $QUEUE -J $JOB_NAME $OUTPUT $POD_LOCATION/etc/Job.lsf
 elif  [ "$RMS" = "pbs" ]; then
-  # PBS
-  # 
-  # A job array parameter is different in PBS (torque) and PBS pro, it is -t and -J accordingly
-  # We try to check a version of PBS to figure out, what to use
-  pbs_pro=$(pbsnodes --version 2>&1 | grep -o PBSPro)
-  pbs_job_array_param="-J 1-$NUM_WRK"
-  if [ -z $pbs_pro ]; then
-    pbs_job_array_param="-t 1-$NUM_WRK"
-  fi
+   #
+   # PBS
+   # 
+   # A job array parameter is different in PBS (torque) and PBS pro, it is -t and -J accordingly
+   # We try to check a version of PBS to figure out, what to use
+   pbs_pro=$(pbsnodes --version 2>&1 | grep -o PBSPro)
+   pbs_job_array_param="-J 1-$NUM_WRK"
+   if [ -z $pbs_pro ]; then
+      pbs_job_array_param="-t 1-$NUM_WRK"
+   fi
 
-  POD_PBS_SHARED_HOME=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key pbs_plugin.shared_home)
-  # if shared home is in use, we command that all of the environment variables of the process
-  # are exported to the context of the batch job. We therefore use -V parameter
-  if [ $POD_PBS_SHARED_HOME -eq 0 ]; then
-    jobid=$(qsub -N pod -q $QUEUE $pbs_job_array_param -j oe -o $LOG_DIR/ -v "POD_UI_LOCATION=$POD_LOCATION, POD_UI_LOG_LOCATION=$LOG_DIR, POD_PBS_SHARED_HOME=$POD_PBS_SHARED_HOME" $POD_LOCATION/etc/Job.pbs)
-  else
-    jobid=$(qsub -N pod -q $QUEUE $pbs_job_array_param -j oe -o $LOG_DIR/ -V -v "POD_UI_LOCATION=$POD_LOCATION, POD_UI_LOG_LOCATION=$LOG_DIR, POD_PBS_SHARED_HOME=$POD_PBS_SHARED_HOME" $POD_LOCATION/etc/Job.pbs)
-  fi
-# we need to create a logs output dir
-  stat=$?
-  if test $stat -eq 0; then
-    echo "Job ID: $jobid"
-    PARENT_PBS_JOBID=$(echo $jobid | egrep -o '^[[:digit:]]*')
-    mkdir -p  $LOG_DIR/$PARENT_PBS_JOBID
-  else
-    echo "Error submitting job. $jobid"
-  fi
+   jobid=$(qsub -N pod -q $QUEUE $pbs_job_array_param -j oe -o $LOG_DIR/ -V -v "POD_UI_LOCATION=$POD_LOCATION, POD_UI_LOG_LOCATION=$LOG_DIR" $POD_LOCATION/etc/Job.pbs)
+   # we need to create a logs output dir
+   if (( $? == 0 )); then
+      echo "Job ID: $jobid"
+      PARENT_PBS_JOBID=$(echo $jobid | egrep -o '^[[:digit:]]*')
+      mkdir -p  $LOG_DIR/$PARENT_PBS_JOBID
+   else
+      echo "Error submitting job. $jobid"
+   fi
  
 elif [ "$RMS" = "oge" ]; then
-  # SGE/OGE
-  #
-  # We assume, that shared home file system is used.
-  # qsub with parameters:
-  # -V          export all environment variables
-  # -terse      tersed output, print only the job-id
-  # -j yes      merge std out and err to one file
-  OGE_OPTION_FILE="$POD_LOCATION/etc/Job.oge.option"
-  oge_job_array_param="-t 1-$NUM_WRK"
-  job_name="PoD_OGE_Job"
-  # OGE option file
-  if [ -r $OGE_OPTION_FILE ]; then
-     OGE_USE_OPTION_FILE=" -@ $OGE_OPTION_FILE"
-  fi
-  jobid=$(qsub -j yes -V -N $job_name -terse $oge_job_array_param -q $QUEUE -o $LOG_DIR $OGE_USE_OPTION_FILE $POD_LOCATION/etc/Job.oge)
-  # we need to create a logs output dir
-  stat=$?
-  # extract a job id only, without an array indexes
-  jobid=$(echo $jobid | cut -f3 -d" " | cut -f1 -d.)
-  if test $stat -eq 0; then
-    echo "Job ID: $jobid"
-    mkdir -p  $LOG_DIR/$jobid
-  else
-    echo "Error submitting job. $jobid"
-  fi
+   #  
+   # SGE/OGE
+   #
+   # We assume, that shared home file system is used.
+   # qsub with parameters:
+   # -V          export all environment variables
+   # -terse      tersed output, print only the job-id
+   # -j yes      merge std out and err to one file
+   OGE_OPTION_FILE="$POD_LOCATION/etc/Job.oge.option"
+   oge_job_array_param="-t 1-$NUM_WRK"
+   job_name="PoD_OGE_Job"
+   # OGE option file
+   if [ -r $OGE_OPTION_FILE ]; then
+      OGE_USE_OPTION_FILE=" -@ $OGE_OPTION_FILE"
+   fi
+   jobid=$(qsub -j yes -V -N $job_name -terse $oge_job_array_param -q $QUEUE -o $LOG_DIR $OGE_USE_OPTION_FILE $POD_LOCATION/etc/Job.oge)
+   # we need to create a logs output dir
+   stat=$?
+   # extract a job id only, without an array indexes
+   jobid=$(echo $jobid | cut -f3 -d" " | cut -f1 -d.)
+   if (( $stat == 0 )); then
+      echo "Job ID: $jobid"
+      mkdir -p  $LOG_DIR/$jobid
+   else
+      echo "Error submitting job. $jobid"
+   fi
 
 fi
 
 exit 0
+
