pod: Remove tmp directories on server and WNs when cleaning. (Bug 22)

diff --git a/bin/pod-server b/bin/pod-server
--- a/bin/pod-server
+++ b/bin/pod-server
@@ -174,6 +174,25 @@ get_bins()
    popd &> /dev/null
 }
 #=============================================================================
+# ***** delete_tmp_dir  *****
+#=============================================================================
+delete_tmp_dir()
+{
+   local old_tmp_holder="$WORK_DIR/./xproofd.tmp"
+
+   # delete the previous tmp dir
+   if [ -r "$old_tmp_holder" ]; then 
+      local old_tmp=$(cat "$old_tmp_holder")
+      if [ -L "$old_tmp" ]; then
+         echo "Security Error: tmp directory of the previous session is a symbolic link."
+         exit 1
+      fi
+      if [ -d "$old_tmp" ]; then
+         rm -rf "$old_tmp"
+      fi
+   fi
+}
+#=============================================================================
 # ***** create_dir  *****
 #=============================================================================
 create_dir()
@@ -198,22 +217,18 @@ create_dir_hierarchy()
 # ************************************************************************
 update_xpd_cfg()
 {
-   # We renew the xpd conf every time PoD server is restart.
+   # We renew the xpd conf every time PoD server is restarted.
    # It is needed since otherwise it will be difficult (if ever possible)
    # to find out, which xproofd was started exactly by this server.
    # PoD and AliEn integration, for example, require, that several PoD
    # servers can be started on one machine under the same user account.
 
-   local old_tmp_holder="$WORK_DIR/.xproofd.tmp"
+   local old_tmp_holder="$WORK_DIR/./xproofd.tmp"
    local xpd_template="$POD_LOCATION/etc/xpd.cf.in"
 
    # 1. delete the previous tmp dir
-   if [ -r "$old_tmp_holder" ]; then 
-      local old_tmp=$(cat "$old_tmp_holder")
-      if [ -d "$old_tmp" ]; then
-         rm -rf "$old_tmp"
-      fi
-   fi
+   delete_tmp_dir
+
    # 2. copy the template file
    cp $xpd_template $XPD_CFG
    # 3. create new tmp folder
@@ -364,6 +379,9 @@ wait_and_kill()
       fi
       sleep 1
    done
+
+  # delete tmp directory
+  delete_tmp_dir
 }
 # ************************************************************************
 # ***** STOP *****
