PoD WNs now try to use first binaries from PoD UI, if OS, ARCH of Server and UI are the same and a shared home file system is detected. It speeds up the start up time of PoD jobs. If this try fails, PoD WN will use pre-compiled bins, which come with PoD' worker package.

diff --git a/bin/pod-prep-worker b/bin/pod-prep-worker
--- a/bin/pod-prep-worker
+++ b/bin/pod-prep-worker
@@ -17,6 +17,7 @@
 ARC_NAME="$POD_LOCATION/etc/pod-worker.tar"
 ARC_NAME_GZ=$ARC_NAME".gz"
 USER_SCRIPT="$POD_LOCATION/etc/user.worker_env.sh"
+WN_BINS="$POD_LOCATION/bin/wn_bins/*"
 #=============================================================================
 # ***** MAIN  *****
 #=============================================================================
@@ -25,10 +26,10 @@ echo "preparing PoD worker package..."
 
 # first delete a previous archive if available
 if [ -f $ARC_NAME ]; then
-  rm -rf $ARC_NAME
+   rm -rf $ARC_NAME
 fi
 if [ -f $ARC_NAME_GZ ]; then
-  rm -rf $ARC_NAME_GZ
+   rm -rf $ARC_NAME_GZ
 fi
 
 # check that all needed components are available
@@ -42,22 +43,23 @@ COMPONENTS=(  "${COMPONENTS_ETC[@]}" )
 # create an empty archive first
 tar cvf $ARC_NAME --files-from=/dev/null 
 
+# add all default components
 for i in "${COMPONENTS[@]}"
 do
-  if [ -f $i ]; then
-    tar --append --file=$ARC_NAME -C $(dirname $i) $(basename $i)
-    RET_VAL=$?
-    if [ "X$RET_VAL" = "X0" ]; then
-	continue
-    else
-	echo "failed. Exit code: $RET_VAL" >&2
-	exit 1
-    fi
-  else
-    echo "Error: missing component: $i" >&2
-    rm -rf $ARC_NAME
-    exit 1
-  fi
+   if [ -f $i ]; then
+      tar --append --file=$ARC_NAME -C $(dirname $i) $(basename $i)
+      RET_VAL=$?
+      if [ "X$RET_VAL" = "X0" ]; then
+	 continue
+      else
+	 echo "failed. Exit code: $RET_VAL" >&2
+	 exit 1
+      fi
+   else
+      echo "Error: missing component: $i" >&2
+      rm -rf $ARC_NAME
+      exit 1
+   fi
 done
 
 # add user's script if present
@@ -66,8 +68,21 @@ if [ -r $USER_SCRIPT ]; then
    tar --append --file=$ARC_NAME -C $(dirname $USER_SCRIPT) $(basename $USER_SCRIPT)
 fi
 
+# add all pre-compiled bins
+echo "Adding pre-compiled bins to worker package..."
+for i in ${WN_BINS[@]} 
+do
+   tar --append --file=$ARC_NAME -C $(dirname $i) $(basename $i)
+   RET_VAL=$?
+   if [ "X$RET_VAL" != "X0" ]; then
+      echo "failed. Exit code: $RET_VAL" >&2
+      exit 1
+   fi
+done
 
+# compress the archive
 gzip -9 $ARC_NAME
 echo "finished successfully: "$ARC_NAME_GZ
 
 exit 0
+
diff --git a/bin/pod-server b/bin/pod-server
--- a/bin/pod-server
+++ b/bin/pod-server
@@ -17,7 +17,12 @@
 # Usage:
 #      pod-server start|stop|status
 #
-
+#
+# Notes:
+# On start the script will check whether WNs pre-compiled bins are present, if not, it will down load them.
+# Users could provide own version of the pre-compiled bins and avoid of downloading of them.
+# 
+#
 #######
 XPROOF_PORTS_RANGE_MIN=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.xproof_ports_range_min)
 XPROOF_PORTS_RANGE_MAX=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.xproof_ports_range_max)
@@ -29,6 +34,8 @@ eval WORK_DIR=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.work
 XPD_START_TIMEOUT=3
 
 SERVER_HOST_NAME=$(hostname -f)
+SERVER_ARCH=$(uname -m  2>&1)
+SERVER_OS=$(uname -s 2>&1)
 
 # getting the version of PoD
 PKG_VERSION=$(cat $POD_LOCATION/etc/version)
@@ -97,7 +104,7 @@ get_freeport()
     exit 1
 }
 # ************************************************************************
-# ***** returns a free port from a given range  *****
+# ***** create PoD server info file  *****
 # takes two parameters, pod agent server host name and port number
 # ************************************************************************
 create_agent_server_info_file()
@@ -106,6 +113,8 @@ create_agent_server_info_file()
     echo "[server]" > $SERVERINFO_FILE
     echo "host=$1" >> $SERVERINFO_FILE
     echo "port=$2" >> $SERVERINFO_FILE
+    echo "os=$SERVER_OS" >> $SERVERINFO_FILE
+    echo "arch=$SERVER_ARCH" >> $SERVERINFO_FILE
 }
 # ************************************************************************
 # ***** Get pre-compiled bins for WNs  *****
@@ -231,6 +240,10 @@ start()
     # Prepare the worker package
     ####
     $POD_LOCATION/bin/pod-prep-worker
+    if [ "X$?" != "X0" ]; then
+       echo "Error: Can't start PoD server. Please check pod-agent.server.log and xpd.log for more information."
+       return 1
+    fi
 
     return 0
 }
