implementing an install-for-all-users feature

diff --git a/bin/pod-info b/bin/pod-info
--- a/bin/pod-info
+++ b/bin/pod-info
@@ -20,7 +20,11 @@
 # -c : print a PROOF connection string, which can be used in TProof::Open
 
 #######
-eval PROOF_CFG=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.proof_cfg_path)
+eval PROOF_CFG=$(pod-user-defaults --key server.proof_cfg_path)
+if (( $? != 0 )) ; then
+   echo "erro: Can't use PoD user defaults."
+   exit 1
+fi
 
 VERSION_FILE="${POD_LOCATION}/etc/version"
 if [ -z "${POD_LOCATION}" ]; then
diff --git a/bin/pod-prep-worker b/bin/pod-prep-worker
--- a/bin/pod-prep-worker
+++ b/bin/pod-prep-worker
@@ -13,10 +13,14 @@
 #*************************************************************************/
 #
 # Usage: pod-prep-worker 
-
-ARC_NAME="$POD_LOCATION/etc/pod-worker.tar"
+#
+# Comment:
+#    The worker package is saved to PoD server working directory.
+#
+eval ARC_DIR=$(pod-user-defaults --key server.work_dir)
+ARC_NAME="$ARC_DIR/pod-worker.tar"
 ARC_NAME_GZ=$ARC_NAME".gz"
-USER_SCRIPT="$POD_LOCATION/etc/user.worker_env.sh"
+USER_SCRIPT=$(pod-user-defaults --userenvscript)
 WN_BINS="$POD_LOCATION/bin/wn_bins/*"
 #=============================================================================
 # ***** MAIN  *****
@@ -24,6 +28,10 @@ WN_BINS="$POD_LOCATION/bin/wn_bins/*"
 
 echo "preparing PoD worker package..."
 
+if [ ! -d "$ARC_DIR" ]; then
+   mkdir -p "$ARC_DIR"
+fi
+   
 # first delete a previous archive if available
 if [ -f $ARC_NAME ]; then
    rm -rf $ARC_NAME
@@ -32,9 +40,15 @@ if [ -f $ARC_NAME_GZ ]; then
    rm -rf $ARC_NAME_GZ
 fi
 
+POD_CFG=$(pod-user-defaults -p)
+if [ -z "$POD_CFG" ]; then
+   echo "error: can't find PoD user defaults"
+   exit 1
+fi
+
 # check that all needed components are available
 COMPONENTS_ETC=( "$POD_LOCATION/etc/xpd.cf" 
-             "$POD_LOCATION/etc/PoD.cfg"
+             "$POD_CFG"
              "$POD_LOCATION/etc/version"
              "$POD_LOCATION/etc/server_info.cfg" )
 
@@ -63,7 +77,7 @@ do
 done
 
 # add user's script if present
-if [ -r $USER_SCRIPT ]; then
+if [ -r "$USER_SCRIPT" ]; then
    echo "Adding a user defined environment script to worker package..."
    tar --append --file=$ARC_NAME -C $(dirname $USER_SCRIPT) $(basename $USER_SCRIPT)
 fi
diff --git a/bin/pod-server b/bin/pod-server
--- a/bin/pod-server
+++ b/bin/pod-server
@@ -27,11 +27,17 @@
 # 
 #
 #######
-XPROOF_PORTS_RANGE_MIN=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.xproof_ports_range_min)
-XPROOF_PORTS_RANGE_MAX=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.xproof_ports_range_max)
-PROOFAGENT_PORTS_RANGE_MIN=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.agent_ports_range_min)
-PROOFAGENT_PORTS_RANGE_MAX=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.agent_ports_range_max)
-eval WORK_DIR=$(pod-user-defaults -c $POD_LOCATION/etc/PoD.cfg --key server.work_dir)
+POD_CFG=$(pod-user-defaults -p)
+if [ -z "$POD_CFG" ]; then
+   echo "error: can't find PoD user defaults"
+   exit 1
+fi
+#######
+XPROOF_PORTS_RANGE_MIN=$(pod-user-defaults --key server.xproof_ports_range_min)
+XPROOF_PORTS_RANGE_MAX=$(pod-user-defaults --key server.xproof_ports_range_max)
+PROOFAGENT_PORTS_RANGE_MIN=$(pod-user-defaults --key server.agent_ports_range_min)
+PROOFAGENT_PORTS_RANGE_MAX=$(pod-user-defaults --key server.agent_ports_range_max)
+eval WORK_DIR=$(pod-user-defaults --key server.work_dir)
 #######
 # a number of seconds we wait until xpd is started 
 XPD_START_TIMEOUT=3
@@ -247,7 +253,7 @@ start()
     # Start pod-agent
     ####
     echo "starting PoD agent..."
-    $POD_LOCATION/bin/pod-agent -d -m server -c $POD_LOCATION/etc/PoD.cfg --start
+    $POD_LOCATION/bin/pod-agent -d -m server -c "$POD_CFG" --start
 
     # Prepare the worker package
     ####
@@ -281,7 +287,7 @@ stop()
     my_pkill xproofd
     my_pkill proofserv
 
-    $POD_LOCATION/bin/pod-agent -d -c $POD_LOCATION/etc/PoD.cfg --stop
+    $POD_LOCATION/bin/pod-agent -d -c "$POD_CFG" --stop
     
     return 0
 }
